
version: "3.7"
services:
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    volumes:
      - ./config:/config
      - ${DIRECTORY_TO_SYNC}:/mnt/sync
    ports:
      - 22000:22000
      - 21027:21027/udp
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    labels:
      - "traefik.port=8384"
      - "traefik.docker.network=frontend"
      - "traefik.enable=true"
      - "traefik.http.routers.sync-http.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.sync-http.entrypoints=http"
      - "traefik.http.routers.sync-http.middlewares=redirect"
      - "traefik.http.routers.sync-https.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.sync-https.entrypoints=websecure"
      - "traefik.http.routers.sync-https.tl.scertresolver=myresolver"
      - "traefik.http.services.sync.loadbalancer.server.port=8384"
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
    networks:
      - frontend
    restart: always


networks:
  frontend:
    external: true


