# docker-compose config | docker stack deploy --compose-file - 

# docker stack rm Syncthing 
# git pull 
# docker-compose config >> docker-compose-gdnafr.yml
# docker stack deploy -c docker-compose-gdnafr.yml Syncthing
# docker service logs -f Syncthing_syncthing

version: "3.7"
services:
  syncthing:
    # image: linuxserver/syncthing:latest
    image: ghcr.io/linuxserver/syncthing
    volumes:
      - ./config:/config
      - ${DIRECTORY_TO_SYNC}:/mnt/sync
    ports:
      - 22000:22000
      - 21027:21027/udp
    networks:
      - traefik-kim
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.docker.network=traefik-kim"
        - "traefik.port=8384"
        - "traefik.backend.loadbalancer.stickiness=true"
        - "traefik.frontend.rule=Host:${DOMAIN}"
        - "traefik.enable=true"


networks:
  traefik-kim:
    external:
      name: traefik-kim