
version: "3.7"
services:
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    volumes:
      - ./config:/config
      - ${DIRECTORY_TO_SYNC}:/mnt/sync
    ports:
      - 22000:22000
      - 21027:21027/udp
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"

      - "traefik.http.routers.test_machine-http.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.test_machine-http.entrypoints=entrypoints-http"
      - "traefik.http.routers.test_machine-http.middlewares=redirect"
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"

      - "traefik.http.routers.test_machine-https.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.test_machine-https.entrypoints=entrypoints-https"
      - "traefik.http.routers.test_machine-https.tls.certresolver=myresolver"

      - "traefik.http.services.test_machine.loadbalancer.server.port=8384"
      
    networks:
      - frontend
    restart: always


networks:
  frontend:
    external: true


