
version: "3.7"
services:
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    volumes:
      - ./config:/config
      - ${DIRECTORY_TO_SYNC}:/mnt/sync
    ports:
      - 22000:22000
      - 21027:21027/udp
      - 8384:8384
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    labels:
      - traefik.http.routers.my-container.rule=Host(`sync.tibillet.re`)
      - traefik.http.services.my-service.loadbalancer.server.port=8384
    networks:
      - frontend
    restart: always


networks:
  frontend:
    external: true


