
version: "3.7"
services:
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    volumes:
      - ./config:/config
      - ${DIRECTORY_TO_SYNC}:/mnt/sync
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    environment:
      - PUID=0
      - PGID=0
      - TZ=Indian/Reunion
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.syncthing.tls.certresolver=myresolver
      - traefik.http.routers.syncthing.rule=Host(`$DOMAIN`)
      - traefik.http.services.syncthing.loadbalancer.server.port=8384

    networks:
      - frontend
    restart: always


networks:
  frontend:
    external: true


